### ISSUE TITLE
Write e2e test for createCoreV1NamespacedPodBinding +1 Endpoint

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#33]
Kanban ticket [194](https://kanban.ii.coop/project/3/task/194)

**Comment by heyste** [comment]
Current research for `createCoreV1NamespacedPodBinding` endpoint is tracked in [kb194.org](https://github.com/apisnoop/ticket-writing/blob/research/kb194.org) file.

**Comment by Riaankl** [comment]
The endpoint was conformance tested by the test '[sig-node] Pods should delete a collection of pods [Conformance]'. This endpoint is hit during the test, but by kube-scheduler and not the testing useragent. APISnoop was updated to refect this after discussion in the [K8s Conformance mailing list](https://groups.google.com/g/kubernetes-conformance/c/e8HgipWLnIA/m/sdBAYaceAQAJ) and [SIG Ach meeting](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit) of 12 Jan 2023
