### ISSUE TITLE
Write e2e test for Get & Post NamespacedPodAttach +2 Endpoints

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#35]
Kanban Ticket [#240](https://kanban.ii.coop/project/3/task/240)

**Comment by heyste** [comment]
Current research for PodAttach endpoints are tracked in [kb240.org](https://github.com/apisnoop/ticket-writing/blob/research/kb240.org) file.

Found that e2e test  "should support inline execution and attach" uses `framework.NewKubectlCommand` which then hits `connectCoreV1PostNamespacedPodAttach` endpoint.

**Comment by heyste** [comment]
Working through the `attach` code base and building a mental model of how it's all wired together. Referring to the `exec` code base as well so I can create an initial alpha test for these endpoints.

**Comment by heyste** [comment]
The following creates an environment([*](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container)) will use one of the "podAttach" api endpoints
```
$ kubectl run ephemeral-demo --image=registry.k8s.io/pause:3.1 --restart=Never
pod/ephemeral-demo created

$ kubectl debug -it ephemeral-demo --image=busybox:1.28 --target=ephemeral-demo
Targeting container "ephemeral-demo". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-5mtkf.
If you don't see a command prompt, try pressing enter.
/ #
```
Using [apisnoop](https://github.com/cncf/apisnoop/tree/main/kind#setup) shows that one pod attach endpoint has been hit via `kubectl`
```
select distinct substring(endpoint from '\w+') AS endpoint, right(useragent,90) AS useragent from
 testing.audit_event where endpoint ilike '%attach%' and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 40000
 and useragent ilike '%' order by endpoint limit 20;

               endpoint               |                    useragent
--------------------------------------+--------------------------------------------------
 connectCoreV1PostNamespacedPodAttach | kubectl/v1.26.0 (linux/amd64) kubernetes/b46a3f8
(1 row)
```
Exploring [kubectl/pkg/cmd/debug](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/cmd/debug) further as I work to convert this to an initial e2e test

**Comment by heyste** [comment]
Noting, a `connectCoreV1PostNamespacedPodAttach` event:

```
"requestURI": "/api/v1/namespaces/default/pods/ephemeral-demo/attach?container=debugger-5mtkf&stdin=true&stdout=true&tty=true"
```

**Comment by Riaankl** [comment]
Made ineligble
https://github.com/kubernetes/kubernetes/issues/112778#issuecomment-1427995711
