### ISSUE TITLE
Write e2e test for createAuthorizationV1Subject & LocalSubject AccessReview +2 Endpoints

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#36]
Kanban Ticket [#202](https://kanban.ii.coop/project/3/task/202)

**Comment by heyste** [comment]
[SIG-Auth Meeting](https://github.com/apisnoop/ticket-writing/issues/36) on these two endpoints.

**Comment by heyste** [comment]
Current research for auth endpoints is tracked in [kb202.org](https://github.com/apisnoop/ticket-writing/blob/research/kb202.org) file.

**Comment by heyste** [comment]
e2e test created and approved in [Write e2e test for SubjectAccessReview & createAuthorizationV1NamespacedLocalSubjectAccessReview +2 Endpoints
#114345](https://github.com/kubernetes/kubernetes/pull/114345)

**Comment by heyste** [comment]
Tracking the progress of the e2e test before it's promoted to conformance

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&graph-metrics=test-duration-minutes&include-filter-by-regex=should.support.SubjectReview.API.operations

**Comment by heyste** [comment]
Update current e2e test as part of the promotion process.

- https://github.com/ii/kubernetes/blob/promote-subjectaccessreview-test/test/e2e/auth/subjectreviews.go#L38-L50
