### ISSUE TITLE
Write e2e test for  APIService lifecycle test + 4 Endpoints

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#37]
Kanban Ticket [#121](https://kanban.ii.coop/project/3/task/121)

**Comment by heyste** [comment]
Historical work on these endpoints is documented in [conformance-progress-for-apiservice-endpoints.org](https://github.com/apisnoop/ticket-writing/blob/research/conformance-progress-for-apiservice-endpoints.org).

The document also has a number of current question on what's the best way forward for testing these endpoints.
- Would it be feasible to use [IsRBACEnabled](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/auth/helpers.go#L150-L167) to wrap all the RBAC calls in [aggregator.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/aggregator.go)?
- Would we need to recreate the APIService endpoints before testing deleteCollection ?
- Is polling the APIService backend as stated earlier a valid fix for now? or would the current bug need to be addressed before the patch status endpoint can be part of Conformance?
- Are there any other issues that should be considered when making the next e2e test?

**Comment by heyste** [comment]
Wrapped RBAC calls to only happen if RBAC is enabled.

https://github.com/heyste/kubernetes/blob/create-apiservice-test-v4/test/e2e/apimachinery/aggregator.go#L135

**Comment by heyste** [comment]
Extended the above e2e test to test following endpoints

- `replaceApiregistrationV1APIServiceStatus`
- `replaceApiregistrationV1APIService`
- `deleteApiregistrationV1CollectionAPIService`

[Commit history for these changes](https://github.com/heyste/kubernetes/commits/create-apiservice-test-v4/test/e2e/apimachinery/aggregator.go)

- `patchApiregistrationV1APIServiceStatus` is missing the verification (watch) checks but is getting tracked by apisnoop.

```
                  endpoint                   |                                            useragent                                            
---------------------------------------------+-------------------------------------------------------------------------------------------------
 createApiregistrationV1APIService           | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 deleteApiregistrationV1APIService           | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 deleteApiregistrationV1CollectionAPIService | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 listApiregistrationV1APIService             | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 patchApiregistrationV1APIService            | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 patchApiregistrationV1APIServiceStatus      | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 readApiregistrationV1APIService             | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 readApiregistrationV1APIServiceStatus       | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 replaceApiregistrationV1APIService          | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
 replaceApiregistrationV1APIServiceStatus    | Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
(10 rows)
```

**Comment by heyste** [comment]
Latest commit messages from today
- Use the provided context from ginkgo
- Refactor/confirm that apiservice status was patched
- Refactor process of confirming apiservice status update
- Focus logging to report the current condition

**Comment by heyste** [comment]
The following PR and issue can been created to address the missing 4 endpoints.

- https://github.com/kubernetes/kubernetes/pull/115214
- https://github.com/kubernetes/kubernetes/issues/115213

Waiting on feedback from SIG-API Machinery

**Comment by heyste** [comment]
- Review and address the feedback provided by Jordan.
- Test changes on both single and HA clusters
- Push changes to PR repo

**Comment by Riaankl** [comment]
![image](https://user-images.githubusercontent.com/61125752/215874554-4ba0c783-33cb-4b46-b10d-38ddba40fd92.png)

![image](https://user-images.githubusercontent.com/61125752/215874955-900a3e2c-8092-4bda-b791-f14c5ca0524d.png)

Almost there!!
