### ISSUE TITLE
Write e2e test for get*APIResources +12 Endpoints

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#42]
The introduction of [Add OpenAPI V3 E2E Tests #116200](https://github.com/kubernetes/kubernetes/pull/116200) caused the `get * V1APIResources` endpoint to show up as untested.

- getAutoscalingV1APIResources
- getAutoscalingV2APIResources
- getPolicyV1APIResources
- getEventsV1APIResources
- getCoordinationV1APIResources
- getSchedulingV1APIResources
- getApiregistrationV1APIResources
- getAppsV1APIResources
- getAuthenticationV1APIResources
- getAuthorizationV1APIResources
- getBatchV1APIResources
- getCoreV1APIResources

To be e2e & conformance tested in 1.28

**Comment by heyste** [comment]
- Created: [Explore APIResources endpoints #55](https://github.com/apisnoop/ticket-writing/pull/55)
- Cleaned up initial e2e test for these endpoints ["should locate the groupVersion and a resource within each APIResource"](https://github.com/ii/kubernetes/blob/create-apiresources-test/test/e2e/apimachinery/discovery.go#L161-L273)

**Comment by heyste** [comment]
Updated the test to also check the following endpoints
```
getAdmissionregistrationV1APIResources
getApiextensionsV1APIResources
getCertificatesV1APIResources
getDiscoveryV1APIResources
getNetworkingV1APIResources
getNodeV1APIResources
getStorageV1APIResources
```

**Comment by heyste** [comment]
Test Grid Link: [should locate the groupVersion and a resource within each APIGroup](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&graph-metrics=test-duration-minutes&include-filter-by-regex=should.locate.the.groupVersion.and.a.resource.within.each.APIGroup)

**Comment by Riaankl** [comment]
Promotion PR merge!
Great work @heyste
