### ISSUE TITLE
Write e2e test for NamespacedPodEphemeralcontainers +2 Endpoints

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#43]
#### Endpoints:
readCoreV1NamespacedPodEphemeralcontainers
replaceCoreV1NamespacedPodEphemeralcontainers

#### Information:
patchCoreV1NamespacedPodEphemeralcontainers This endpoint was tested in v1.25 and could be looked at to guide the test for the read and replace endpoints.

**Comment by heyste** [comment]
- e2e test: [ginkgo.It("should update the ephemeral containers in an existing pod", func(ctx context.Context) { ... })](https://github.com/kubernetes/kubernetes/blob/bb67eb5bd237334d6d0343aa382b351002653404/test/e2e/common/node/ephemeral_containers.go#L90-L161)
- Test Grid link: ["should update the ephemeral containers in an existing pod"](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&graph-metrics=test-duration-minutes&include-filter-by-regex=should.update.the.ephemeral.containers.in.an.existing.pod)

**Comment by Riaankl** [comment]
Promotion PR Merged.
Great work @heyste
