### ISSUE TITLE
Write e2e test for VolumeAttachment +7 Endpoints

### ISSUE THREAD

**Issue by Riaankl** [apisnoop/ticket-writing#53]
#### Endpoints:
createStorageV1VolumeAttachment
readStorageV1VolumeAttachment
listStorageV1VolumeAttachment
patchStorageV1VolumeAttachment
replaceStorageV1VolumeAttachment
deleteStorageV1VolumeAttachment
deleteStorageV1CollectionVolumeAttachment

**Comment by heyste** [comment]
- Issue: [Write e2e test for VolumeAttachment endpoints +7 Endpoints #122116](https://github.com/kubernetes/kubernetes/issues/122116)
- PR:  [Create e2e test for VolumeAttachment endpoints #122117](https://github.com/kubernetes/kubernetes/pull/122117)

**Comment by heyste** [comment]
- PR: [Promote e2e test for VolumeAttachment Endpoints + 7 Endpoints](https://pr.k8s.io/123942)

**Comment by heyste** [comment]
Completed!
