### ISSUE TITLE
Write e2e test for VolumeAttachmentStatus +3 Endpoints

### ISSUE THREAD

**Issue by riaankleinhans** [apisnoop/ticket-writing#54]
#### Endpoints:
readStorageV1VolumeAttachmentStatus
patchStorageV1VolumeAttachmentStatus
replaceStorageV1VolumeAttachmentStatus

**Comment by heyste** [comment]
Completed
- https://github.com/kubernetes/kubernetes/issues/126826
- https://github.com/kubernetes/kubernetes/pull/127458
